# Parte 01

Nessa sessão introdutória veremos:
- O que é o Pandas
- Pandas x Excel (comparativo)
- Principais conceitos
- Criação de colunas e uso de funções

## 1.1 - Introdução

O objetivo deste notebook é desenvolver uma compreensão sólida dos fundamentos do pandas através da exploração prática do dataset do Titanic Dataset.

Mais do que aprender comandos isolados, o foco será compreender a lógica estrutural do Pandas, incluindo:

- DataFrames e Series
- Vetorização
- Índices e alinhamento de dados
- Seleção e filtragem com .loc e .iloc
- Máscaras booleanas
- Tipos de dados (dtype)
- Tratamento de valores ausentes (NaN)

Ao longo da análise, o objetivo será abandonar a mentalidade de manipulação célula a célula, comum em planilhas, e passar a enxergar os dados como estruturas vetorizadas organizadas em colunas (Series) alinhadas por índices.

O notebook também servirá como registro de aprendizado progressivo, conectando conceitos teóricos à prática analítica em dados reais.

### 1.1.2 - O que é pandas

O pandas é uma biblioteca do Python voltada para manipulação e análise de dados estruturados.

Sua principal estrutura é o DataFrame, uma tabela bidimensional composta por colunas chamadas Series. Cada Series funciona como um vetor de dados associado a um índice, permitindo operações vetorizadas rápidas e eficientes.

Diferente de planilhas tradicionais, o Pandas não é orientado a células, mas sim a transformações aplicadas sobre conjuntos de dados (vetores/colunas). Isso permite realizar filtragens, agregações, tratamentos de dados ausentes e análises estatísticas de forma escalável e expressiva.

Internamente, o Pandas utiliza amplamente o NumPy para operações vetorizadas e organização eficiente dos dados em memória.

***Documentação:*** (https://pandas.pydata.org/)

#### 1.1.2.1 Vetor
O vetor é uma sequência organizada de valores sobre a qual é possível aplicar operações de forma simultânea.

**Exemplo:**

`[22, 38, 26, 35]`

Em Pandas, uma coluna como:

`df['Age']`

pode ser entendida como um vetor de idades.

A principal característica de um vetor é permitir operações vetorizadas, ou seja, operações aplicadas automaticamente a todos os elementos do conjunto sem necessidade de loops explícitos.

**Exemplo:**

`df['Age'] + 10`

**Resultado conceitual:**

`[22, 38, 26] → [32, 48, 36]`

Assim, no Pandas, os dados deixam de ser tratados célula por célula e passam a ser manipulados como estruturas vetoriais organizadas em colunas (Series).

#### 1.1.2.1 - Series

No pandas, uma Series é uma estrutura unidimensional composta por:

- um vetor de dados
- um índice associado a cada valor

Ela pode ser entendida como a representação de uma única coluna de um DataFrame.

**Exemplo conceitual:**

|Indice|Valor|
|------|-----|
|0|22|
|1|38|
|2|26|


Nesse caso:

- à esquerda está o índice
- à direita estão os valores do vetor

Quando executamos:

`df['Age']`

o retorno é uma Series.

Uma Series permite:

- operações vetorizadas
- alinhamento automático por índice
- filtragens e transformações eficientes

**Estruturalmente:**

Series = índice + vetor de dados

E um DataFrame pode ser entendido como um conjunto de Series alinhadas pelo mesmo índice.

#### 1.1.2.3 - Colunas

No pandas, uma coluna representa uma Series dentro de um DataFrame.

Cada coluna possui:

- um nome (label)
- um índice compartilhado com o restante do DataFrame
- um vetor de dados associado

Exemplo:

`df['Age']`

Nesse caso:

- Age é o nome da coluna
- o retorno é uma Series

Estruturalmente:


```text
DataFrame
 ├── Coluna Age  → Series
 ├── Coluna Fare → Series
 └── Coluna Sex  → Series
```

As colunas são a principal unidade de trabalho no Pandas, permitindo operações vetorizadas, filtragens, agregações e transformações de dados de forma eficiente.

#### 1.1.2.4 - DataFrame

O DataFrame é uma estrutura tabular bidimensional composta por múltiplas Series alinhadas por um mesmo índice.
Cada coluna do DataFrame é uma Series, e cada Series contém:

- um vetor de dados


- um índice associado

Exemplo estrutural:

```
DataFrame
 ├── Coluna Age  → Series
 ├── Coluna Fare → Series
 └── Coluna Sex  → Series
 ```

O DataFrame é a principal estrutura do Pandas para manipulação e análise de dados, permitindo:


- operações vetorizadas


- filtragens

- agregações

- transformações
- alinhamento automático por índice

Diferente de planilhas tradicionais, o Pandas trabalha orientado a colunas (Series) e operações sobre vetores, e não célula por célula.

## 1.2 - Importação dos dados

In [1]:
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# podemos passar um diretório local( pasta no computador local ou rede) ou na internet.
# Para o nosso estudo, usaremos um arquivo hospedado no Kaggle
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

In [3]:
# o pandas trabalha com diversos tipos de arquivos, um dos mais comuns é o csv
# cada tipo de arquivo tem um método próprio. Consulte o link da documentação para ver todos.
df = pd.read_csv(url)
#nota: para ler um arquivo txt, usamos o read_csv.

### 1.2.1 Conhecendo os dados

In [4]:
#podemos exibir o cabeçalho, primeiras linhas do dataframe usando o comando df.head(X)
# X : número inteiro que informará ao pandas quantas linhas serão retornadas
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [5]:
#para exibir as X últimas linhas, use df.tail(X)
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
#retorna o tipo de dado de cada coluna do dataframe
df.shape

(891, 12)

In [7]:
#retorna o tipo de dados de cada coluna e também a quantidade de valores nulos em cada uma
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
#retorna um dataframe(matriz) de True or False
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [9]:
#No python, o valor False equivale a 0 e o True, a 1.
#Dessa forma é possivel somar os valores em cada coluna
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Nota-se que a coluna com o maior números de nulos é a "Cabin" , cabine.

Essa quantidade de núlos pode significar falha de registro ou uma informação valiosa. No caso, do Titanic, a falta de informação pode significar que apenas os passageiros das classes mais abastadas ficavam em cabines e por isso, havia esse registro.

### 1.2.2 - Series e Dataframes

In [10]:
#selecionar uma coluna indvidual
#retornará uma serie , ou seja: um vetor + metadado + índice
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [11]:
#seleção de coluna múltipla
#retorno: um dataframe.
# DataFrame => conjunto de series
df[['Age', 'Fare']]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

## 1.3 - Localizando e retornando dados

### 1.3.1 Loc - Selecionando a partir de rótulos

`.loc` é o método do Pandas usado para selecionar dados por rótulos (labels) de linhas e colunas.
Sua estrutura é:

`df.loc[linhas, colunas]`

Ele permite:

- filtrar dados com condições booleanas
- acessar linhas e colunas específicas
- modificar valores de forma segura

Diferente do .iloc, o .loc usa nomes/rótulos e não posições numéricas.
Além disso, no slicing ele inclui o valor final.

In [12]:
#retona a primeira linha do dataframe.
# o tipo de dados retornado é uma serie
# lembre-se que indexação em Python começa em 0
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [13]:
#retornando uma linha e uma coluna juntas
# foi retornado o primerio valor da linha 0 e da coluna Idade [matriz X e Y]
# nesse caso, podemos fazer uma analogia com o Excel: retorne a "céluna X da coluna Y"
df.loc[0, 'Age']

np.float64(22.0)

In [14]:
#selecionando várias linhas
df.loc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

###
 1.3.2 Iloc - Selecionando os dados a partir da posição

`.iloc` é o método do Pandas usado para selecionar dados por posição numérica (índice inteiro) de linhas e colunas.

Sua estrutura é:

` df.iloc[linhas, colunas] `

Ele permite:

- acessar dados pela posição física
- selecionar intervalos de linhas e colunas
- trabalhar de forma semelhante ao slicing tradicional do Python

Diferente do .loc, o .iloc não usa rótulos, apenas posições numéricas.
No slicing, o valor final não é incluído.

In [15]:
df.iloc[0, 3]

'Braund, Mr. Owen Harris'

**Extra - Tipo de Dados**

In [16]:
type(df['Age'])

pandas.core.series.Series

In [17]:
type(df[['Age']])

pandas.core.frame.DataFrame

In [18]:
type(df.loc[0])

pandas.core.series.Series

In [19]:
type(df.loc[[0]])

pandas.core.frame.DataFrame

In [20]:
type(df.loc[0, 'Age'])

numpy.float64

## 1.4 - Primeiros Filtros

No pandas, podemos filtras valores de duas formas:
- referenciando a(s) coluna(s) e passando os parâmetros
- usando o método query cuja sintaxe assemelha-se a do SQL

#### 1.4.1 - Filtros simples

In [21]:
df[df['Age'] >= 18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

🧠 O que acontece internamente?

Primeiro: df['Age'] >= 18

gera:
```
True
False
True
...
```

👉 um vetor booleano (máscara)

Depois: `` df[mascara] ``

retorna apenas linhas True.
Esse conceito é central

Pandas funciona MUITO baseado em:
- vetores booleanos
- filtragem vetorizada

In [22]:
#Filtro com loc
df.loc[df['Age'] >= 18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Por que usar .loc?

Porque deixa claro:

- estou filtrando linhas
- estou usando rótulos

#### 1.4.2 -  Selecionando colunas após filtro

In [23]:
df.loc[df['Age'] >= 18, ['Name', 'Age', 'Fare']]

                                                  Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                               Heikkinen, Miss. Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
885               Rice, Mrs. William (Margaret Norton)  39.0  29.1250
886                              Montvila, Rev. Juozas  27.0  13.0000
887                       Graham, Miss. Margaret Edith  19.0  30.0000
889                              Behr, Mr. Karl Howell  26.0  30.0000
890                                Dooley, Mr. Patrick  32.0   7.7500

[601 rows x 3 columns]

#### 1.4.3 Filtros com Mais de uma condição
Use os filtros condicionais abaixo:
|Filtro|Significado|
|------|-----------|
|&|AND|
|\||OR|

In [24]:
df.loc[
    (df['Age'] >= 18) &
    (df['Fare'] > 50)
]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

### 1.4.5 df.query
Embora será possível fazer filtros usando condicionais, o código rapidamente se torna complexo . Nesse cenário que temos a alternativa de usar o método `query()`

**O que é df.query()?**

O método `df.query()` permite filtrar um DataFrame usando expressões em formato de texto, quase como uma mini linguagem de consulta.

**Comparação**
|Forma tradicional| Df Query|
|-----------------|---------|
|df.loc[df['Age'] > 18]|df.query("Age > 18")|
|df.loc[(df['Age'] > 18) <br> &(df['Fare'] > 50)]| df.query("Age > 18 and Fare > 50")|

##### **Notas**
1. Dentro do query usamos ***and*** e **or**
2. Na forma clássica usamos ***&*** e **|**

**Documentação:** (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)

In [25]:
#comparação
df.query("Age > 18")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
#igualdade
df.query("Sex == 'female'")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [27]:
#multiplas condições
df.query("Sex == 'female' and Pclass == 1")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [28]:
#selecionando colunas após o df.query()
df.query("Age > 18")[['Name', 'Age', 'Fare']]

                                                  Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                               Heikkinen, Miss. Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
885               Rice, Mrs. William (Margaret Norton)  39.0  29.1250
886                              Montvila, Rev. Juozas  27.0  13.0000
887                       Graham, Miss. Margaret Edith  19.0  30.0000
889                              Behr, Mr. Karl Howell  26.0  30.0000
890                                Dooley, Mr. Patrick  32.0   7.7500

[575 rows x 3 columns]

#### 1.4.5.1 - Variáveis

Uma das maiores vantagens do método `query()` é a possibilidade de utilizar variáveis externas do Python dentro da expressão de filtragem.

Com isso, o código ganha:

- legibilidade
- clareza
- facilidade de manutenção
- reutilização de filtros dinâmicos

As variáveis externas são referenciadas utilizando o operador `@`.

Exemplo:

```python
idade = 30

df.query("Age > @idade")
```

In [29]:
idade = 25
df.query("Age > @idade")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [30]:
sexo = 'male'
df.query(" Age>= @idade and Sex == @sexo")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
#Filtros multiplos
# após retorna as colunas necessárias

idade_min = 18
idade_max = 40
sexo = 'female'
classes = [1, 2]
tarifa = 50

df.query(
    "(@idade_min <= Age <= @idade_max) "
    "and Sex == @sexo "
    "and Pclass in @classes "
    "and Fare > @tarifa"
)[['Name', 'Age', 'Pclass', 'Fare']]

#note que, embora tenha mais linhas de código, a sintaxe é mais fluída que a forma tradicional:
#df.loc[
#    (df['Sex'] == sexo) &
#    (df['Pclass'].isin(classes)) &
#    (df['Fare'].between(50, 150))
#]

                                                  Name   Age  Pclass      Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1   71.2833
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1   53.1000
61                                 Icard, Miss. Amelie  38.0       1   80.0000
88                          Fortune, Miss. Mabel Helen  23.0       1  263.0000
151                  Pears, Mrs. Thomas (Edith Wearne)  22.0       1   66.6000
215                            Newell, Miss. Madeleine  31.0       1  113.2750
218                              Bazzani, Miss. Albina  32.0       1   76.2917
230       Harris, Mrs. Henry Birkhardt (Irene Wallach)  35.0       1   83.4750
257                               Cherry, Miss. Gladys  30.0       1   86.5000
258                                   Ward, Miss. Anna  35.0       1  512.3292
269                             Bissette, Miss. Amelia  35.0       1  135.6333
290                       Barber, Miss. Ellen "Nellie"  26.0       1   78.8500
291            Bishop, Mrs. Dickinson H (Helen Walton)  19.0       1   91.0792
309                     Francatelli, Miss. Laura Mabel  30.0       1   56.9292
310                     Hays, Miss. Margaret Bechstein  24.0       1   83.1583
311                         Ryerson, Miss. Emily Borie  18.0       1  262.3750
318                           Wick, Miss. Mary Natalie  31.0       1  164.8667
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  40.0       1  134.5000
325                           Young, Miss. Marie Grice  36.0       1  135.6333
341                     Fortune, Miss. Alice Elizabeth  24.0       1  263.0000
356                        Bowerman, Miss. Elsie Edith  22.0       1   55.0000
369                      Aubart, Mme. Leontine Pauline  24.0       1   69.3000
383  Holverson, Mrs. Alexander Oskar (Mary Aline To...  35.0       1   52.0000
393                             Newell, Miss. Marjorie  23.0       1  113.2750
412                             Minahan, Miss. Daisy E  33.0       1   90.0000
486    Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)  35.0       1   90.0000
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0       1  151.5500
520                              Perreault, Miss. Anne  30.0       1   93.5000
537                                LeRoy, Miss. Bertha  30.0       1  106.4250
540                            Crosby, Miss. Harriet R  36.0       1   71.0000
558             Taussig, Mrs. Emil (Tillie Mandelbaum)  39.0       1   79.6500
577          Silvey, Mrs. William Baird (Alice Munger)  39.0       1   55.9000
581  Thayer, Mrs. John Borland (Marian Longstreth M...  39.0       1  110.8833
585                                Taussig, Miss. Ruth  18.0       1   79.6500
609                          Shutes, Miss. Elizabeth W  40.0       1  153.4625
615                                Herman, Miss. Alice  24.0       2   65.0000
627                      Longley, Miss. Gretchen Fiske  21.0       1   77.9583
641                               Sagesser, Mlle. Emma  24.0       1   69.3000
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.0       1  227.5250
708                               Cleaver, Miss. Alice  22.0       1  151.5500
716                      Endres, Miss. Caroline Louise  38.0       1  227.5250
730                      Allen, Miss. Elisabeth Walton  29.0       1  211.3375
742              Ryerson, Miss. Susan Parker "Suzette"  21.0       1  262.3750
759  Rothes, the Countess. of (Lucy Noel Martha Dye...  33.0       1   86.5000
763          Carter, Mrs. William Ernest (Lucile Polk)  36.0       1  120.0000
809     Chambers, Mrs. Norman Campbell (Bertha Griggs)  33.0       1   53.1000
835                        Compton, Miss. Sara Rebecca  39.0       1   83.1583

### 1.4.6 - df.query ou df.loc


Ambos são ferramentas poderosas e devem ser usadas conforme a necessidade.
Comparando as duas, temos:

| **query()**          | **.loc**                |
| ------------------ | --------------------- |
| mais legível       | mais explícito        |
| parece SQL         | mais “Pandas puro”    |
| ótimo para filtros | mais flexível         |
| menos colchetes    | mais controle técnico |

## 1.5 - Funções

### 1.5.1 - Apply()

**O que é apply()?**

O método: `apply()`permite aplicar uma função sobre:
- uma Series
- ou sobre linhas/colunas de um DataFrame

In [32]:
df['Age'].apply(lambda x: x + 10)

0      32.0
1      48.0
2      36.0
3      45.0
4      45.0
       ...
886    37.0
887    29.0
888     NaN
889    36.0
890    42.0
Name: Age, Length: 891, dtype: float64

**O que acontece?**

A coluna Age é uma Series.

O apply():
- pega cada valor
- chama de x

executa: `x + 10`

**Importante**

Isso: `df['Age'] + 10` faz a mesma coisa e normalmente é:
- mais rápido
- mais idiomático
- mais “Pandas

**Primeira grande lição do apply**
  ❌ Não use apply() para operações vetorizáveis simples.

**Então quando ele começa a brilhar?**

Quando sua lógica:
- é complexa
- não existe pronta no Pandas
- exige função customizada

Abaixo um exemplo de uso que exige apply

In [33]:
def categoria_idade(x):
    if x < 18:
        return 'Menor'
    elif x < 60:
        return 'Adulto'
    else:
        return 'Idoso'

In [34]:
df['FaixaEtaria'] = df['Age'].apply(categoria_idade)

**Considerações:**

O que o apply faz aqui?
Para cada idade:
- chama a função
- recebe o retorno
- monta uma nova Series

Ou seja, o apply():
- recebe uma função
- executa várias vezes
- constrói o resultado fina

Isso significa que em Series o `apply()` opera elemento foi elemento

Mas em DataFrame:
- pode operar por coluna
- ou por linha

Para isso, precisamos passar o argumento **axis**

**Axis**

O axis não significa "horizontal" ou "vertical" e sim  a direção da operação

| Axis     | Significado                 |
| -------- | --------------------------- |
| `axis=0` | operar AO LONGO das linhas  |
| `axis=1` | operar AO LONGO das colunas |

Exemplo

|Indice|Age| Fare|
|------|---|-----|
|0|22|7.25|
|1|38|71.83|
|2|26|7.92|

**Axis = 0**

O pandas percorre as colunas ↓
```
Exemplo:
df[['Age', 'Fare']].apply(max, axis=0)
```

```
Age     80
Fare   512
```
**axis=1**

O Pandas percorre as linhas →
```
Exemplo
df[['Age', 'Fare']].apply(sum, axis=1)
```

Para cada linha: Age + Fare


⚠️ Aqui está o ponto CRÍTICO

No axis=0, a função recebe Series de coluna

No axis=1, a função recebe uma Series de linhas

Exemplos:
```
def exemplo(x):
    print(type(x))
```

Com axis=0 , cada x será um coluna interira.

Ex: `df.apply(exemplo, axis=0)`

Com axis=1, cada x será uma linha inteira.

Ex: `df.apply(exemplo, axis=1)`

**Resumo**

| Axis     | A função recebe       |
| -------- | --------------------- |
| `axis=0` | uma coluna (`Series`) |
| `axis=1` | uma linha (`Series`)  |

### 1.5.2 - Diferença entre aplicar em colunas e linhas
#### 1.5.2.1 - Aplicar em colunas (axis=0)

O Pandas entrega uma coluna inteira (Series) por vez.

`df[['Age', 'Fare']].apply(max, axis=0)`

O que a função recebe?
- Perimeiro , a  _Series Age_ e depois a _Series Fare_

Então o foco aqui é operações sobre colunas inteiras

Exemplos:
- média
- máximo
- mínimo
- padronização
- limpeza de texto

### 6.2.2 -  Aplicar em linhas (axis=1)

Agora o Pandas entrega uma linha inteira (Series) por vez.

Exemplo: `df[['Age', 'Fare']].apply(sum, axis=1)`

**Exemplo de uso:**
```
def categoria(row):
    if row['Age'] < 18:
        return 'Menor'
    elif row['Fare'] > 100:
        return 'VIP'
    else:
        return 'Adulto'
```

Aplicação: `df.apply(categoria, axis=1)`


Para cada linha:
- a função recebe a linha inteira
- acessa:
```
row['Age']
row['Fare']
```

Em Axis = 0 , pensamos em **coluna → transformação**

Em Axis = 1 , pensamos em **registro/linha → decisão**


**Conclusão**

Use axis=0, quando:
- trabalha com uma variável isolada
- estatísticas
- limpeza
- transformação vetorizada

Use axis=1 quando:
- precisa combinar colunas
- criar regras condicionais
- tomar decisões por registro


⚠️ ALERTA MUITO IMPORTANTE

O axis=1 costuma ser:
- mais lento
- menos vetorizado
- mais próximo de loop


**Nota:**

Sempre se pergunte: “consigo resolver isso sem axis=1?”

Porque muitas vezes:
- np.where
- máscaras booleanas
- vetorização

são melhores.

## 1.6 - Criação de colunas

Criar coluna no Pandas normalmente significa gerar uma nova Series alinhada ao índice do DataFrame.

**Exemplo mais simples** `df['Age_Double'] = df['Age'] * 2`

#### **O que aconteceu?**
O Pandas:
- pegou a coluna Age
- aplicou operação vetorizada
- criou nova Series
- alinhou pelo índice
- adicionou ao DataFrame

⚠️ Isso NÃO é Excel

Você não está copiando fórmula célula por célula

Você está transformando um vetor inteiro

**Exemplo com condição** `df['Adulto'] = df['Age'] >= 18`

O resultado será uma nova coluna de True or False

**Exemplo com np.where**
```
import numpy as np

df['Faixa'] = np.where(
    df['Age'] >= 18,
    'Adulto',
    'Menor'
)
```

Isso é MUITO usado porque:
- é vetorizado
- rápido
- limpo
- evita apply(axis=1)


**Exemplo mais analítico**
```df['VIP'] = np.where(
    df['Fare'] > 100,
    'Sim',
    'Não'
)
```

Isso é extremamente importante em:
- machine learning
- análise de dados
- engenharia de atributos

**Conceito importante**

Feature engineering:criação de novas colunas derivadas dos dados originais.

⚠️ Regra MUITO importante

Sempre pense:___“essa lógica pode ser vetorizada?"___ antes de usar:

- apply
- loops
- axis=1


**Próximos passos de criação de colunas**
- assign()
- múltiplas condições com np.select
- .map()
- .replace()
- criação com apply()
- diferenças de performance

### 1.6.1 -  assign()

O método `assign()`permite criar colunas sem modificar diretamente o dataframe original

**Comparação**

Forma tradicional: `df['Age_Double'] = df['Age'] * 2`
com assign:
```
df.assign(
    Age_Double = df['Age'] * 2
)
```

O método tradicional modifica o DataFrame, já o `assign()`retorna um novo dataframe

isso é importante no pipelines de dados pois podemos criar novas colunas sem modificar o dataframe original

**Assign()**
Criando múltiplas colunas
```
df.assign(
    Age_Double = df['Age'] * 2,
    Adulto = df['Age'] >= 18
)
```

Isso é diferente do apply()

No apply(), o x pode ser:
- elemento
- linha
- coluna

No assign(), o lambda recebe o DataFrame inteiro

**Vantagens**
Você consegue:
- criar pipelines limpos
- evitar variáveis intermediárias
- escrever código mais fluido

**Quando usar assign()**
- pipelines
- notebooks organizados
- method chaining
- múltiplas transformações

**Atribuição tradicional**

Melhor para:
- exploração rápida
- scripts simples
- debugging

**Extra: método chaining**

Chaining vem da ideia de encadear operações ou criar uma cadeia de métodos.
Exemplo:
```
(
    df
    .query("Age >= 18")
    .assign(VIP = lambda x: x['Fare'] > 100)
    .sort_values('Fare', ascending=False)
)
```
O que acontece
```
DataFrame
   ↓
query()
   ↓
assign()
   ↓
sort_values()
```

Isso aproxima Pandas de pipelines de dados

Muito comum em:
- engenharia de dados
- análise de dados
- notebooks profissionais

Vantagens
- Código mais fluido
- Menos variáveis intermediárias
- Fluxo mais legível
- Mais declarativo

⚠️ Mas existe um cuidado
Chains MUITO grandes podem:
- dificultar debugging
- reduzir clareza

### 1.6.2 - múltiplas condições com np.select
o O np.where() funciona muito bem para `SE / SENÃO`

Mas e quando você precisa de:
```SE
SENÃO SE
SENÃO SE
SENÃO
```
Aí entra o `np.select()` pois ele permite múltiplas condições vetorizadas.
A sintaxe é
```
np.select(
    condicoes,
    escolhas,
    default
)
```
**Exemplo 1**

```
import numpy as np

condicoes = [
    df['Age'] < 18,
    df['Age'] < 60
]

escolhas = [
    'Menor',
    'Adulto'
]

df['FaixaEtaria'] = np.select(
    condicoes,
    escolhas,
    default='Idoso'
)
```

**Exemplo 2**
```
condicoes = [
    df['Fare'] > 100,
    df['Fare'] > 50,
    df['Fare'] > 20
]

categorias = [
    'Luxo',
    'Premium',
    'Intermediário'
]

df['CategoriaTarifa'] = np.select(
    condicoes,
    categorias,
    default='Econômica'
)
```
Isso é MUITO usado em:
- feature engineering
- segmentação
- scoring
- classificação
- regras de negócio

**Comparação**

| Ferramenta    | Melhor uso                  |
| ------------- | --------------------------- |
| `np.where()`  | duas opções                 |
| `np.select()` | múltiplas regras            |
| `apply()`     | lógica customizada complexa |

**Nota**

Muita gente usa `apply(axis=1)` para lógica condicional. No entanto, poderia usar `np.select()`

O `np.select()` é :
- mais rápida
- mais vetorizada
- mais elegante

In [35]:
import numpy as np

condicoes = [
    df['Age'] < 18,
    df['Age'] < 60
]

escolhas = [
    'Menor',
    'Adulto'
]

df['FaixaEtaria'] = np.select(
    condicoes,
    escolhas,
    default='Idoso'
)

In [36]:
condicoes = [
    df['Fare'] > 100,
    df['Fare'] > 50,
    df['Fare'] > 20
]

categorias = [
    'Luxo',
    'Premium',
    'Intermediário'
]

df['CategoriaTarifa'] = np.select(
    condicoes,
    categorias,
    default='Econômica'
)

In [37]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adulto,Econômica
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adulto,Premium
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adulto,Econômica
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adulto,Premium
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adulto,Econômica
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Idoso,Econômica
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Adulto,Premium
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Menor,Intermediário
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adulto,Econômica
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Menor,Intermediário

### 1.6.3 - map()

O `.map()` é usado principalmente para transformar valores de uma Series através de um mapeamento.

**A ideia central é** valor antigo → valor novo

**Exemplo clássico**
```
df['Sex'].map({
    'male': 'Homem',
    'female': 'Mulher'
})

```
O que acontece?
O Pandas percorre a Series:
```
male
female
male
```

e substitui por:
```
Homem
Mulher
Homem
```
Isso é um mapeamento chave → valor. Esse tipo de mapeamente é muito usado para:
- tradução
- categorização
- renomeação
- transformação rápida de valores

**Exemplo numérico**
```df['Survived'].map({
    0: 'Não',
    1: 'Sim'
})
```

⚠️ Comportamento MUITO importante:

Valores não encontrados viram NaN
```
df['Pclass'].map({
    1: 'Primeira'
})
```
**Resultado**
| Valor original | Resultado |
| -------------- | --------- |
| 1              | Primeira  |
| 2              | NaN       |
| 3              | NaN       |


isso ocorre porque o `.map()` procura correspondência exata. Basicamente ele funciona como um **"dicionário vetorizado"**

O  `.map()` também aceita função como `df['Name'].map(len)`. Nesse caso, ele aplica o método `len()` em cada valor da Serie.

⚠️ Mas aqui entra um detalhe importante

Quando usamos função:
.map() e .apply() ficam parecidos.

Diferenças práticas

| Método     | Foco                                  |
| ---------- | ------------------------------------- |
| `.map()`   | transformação simples de uma `Series` |
| `.apply()` | transformações mais gerais/flexíveis  |


**Regra prática MUITO boa**

Use .map() quando:
- transformar valores
- traduzir categorias
- usar dicionário
- operar em UMA coluna

Use .apply() quando:
- lógica mais complexa
- transformação customizada
- múltiplas colunas/linhas

Exemplo real:
```classes = {
    1: 'Primeira Classe',
    2: 'Segunda Classe',
    3: 'Terceira Classe'
}

df['ClasseNome'] = df['Pclass'].map(classes)
```

In [38]:
classes = {
    1: 'Primeira Classe',
    2: 'Segunda Classe',
    3: 'Terceira Classe'
}

df['ClasseNome'] = df['Pclass'].map(classes)

In [39]:
df['Survived'] = df['Survived'].map({
    0: 'Não',
    1: 'Sim'
})

In [40]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa,ClasseNome
0,1,Não,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adulto,Econômica,Terceira Classe
1,2,Sim,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adulto,Premium,Primeira Classe
2,3,Sim,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adulto,Econômica,Terceira Classe
3,4,Sim,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adulto,Premium,Primeira Classe
4,5,Não,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adulto,Econômica,Terceira Classe
5,6,Não,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Idoso,Econômica,Terceira Classe
6,7,Não,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Adulto,Premium,Primeira Classe
7,8,Não,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Menor,Intermediário,Terceira Classe
8,9,Sim,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adulto,Econômica,Terceira Classe
9,10,Sim,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Menor,Intermediário,Segunda Classe

### 1.6.4 - Método replace()
**O que é .replace()?**
O método  `replace()`serve para substituir valores existentes por outros valores.
*Exemplo simples:*
```
df['Sex'].replace({
    'male': 'Homem',
    'female': 'Mulher'
})
```
```
male   → Homem
female → Mulher
```

**nota:**
O `.map()` transforma tudo e os valores não encontrados transformam em NaN. Já o `.replace()` preserva o restante.
```
df['Pclass'].replace({
    1: 'Primeira'
})
```
**Resultado**

| Original | Resultado |
| -------- | --------- |
| 1        | Primeira  |
| 2        | 2         |
| 3        | 3         |

⚠️ Compare com .map()

Com `.map() `2 e 3 virariam NaN

| Método       | Comportamento        |
| ------------ | -------------------- |
| `.map()`     | mapeamento completo  |
| `.replace()` | substituição pontual |


Outro uso MUITO comum  do replace é na limpeza de dados.
Exemplo: `df['Age'].replace(-1, np.nan)`. Ele substitui o -1 por NaN

Múltiplas substituições:
```
df.replace({
    'male': 'M',
    'female': 'F',
    'S': 'Southampton'
})
```
***Notas***
- O `.replace()`Pode operar no DataFrame inteiro Não apenas em Series.
- Também aceita regex: `df['Name'].replace(r'Mr\.', 'Sr.', regex=True)`
- Muito usado em:
  - Limpeza textual
  - padronização
  - tratamento de inconsistências

###**Conclusão:**

⚠️ Regra prática:

Use `.map()` quando:
- quer transformar TODOS os valores
- trabalha com categorias
- aceita NaN para ausentes

Use `.replace()` quando:
- quer trocar apenas alguns valores
- preservar o restante
- fazer limpeza/substituição pontual

In [41]:
df['Sex']= df['Sex'].replace({
    'male': 'Homem',
    'female': 'Mulher'
})

In [42]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa,ClasseNome
0,1,Não,3,"Braund, Mr. Owen Harris",Homem,22.0,1,0,A/5 21171,7.2500,NaN,S,Adulto,Econômica,Terceira Classe
1,2,Sim,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mulher,38.0,1,0,PC 17599,71.2833,C85,C,Adulto,Premium,Primeira Classe
2,3,Sim,3,"Heikkinen, Miss. Laina",Mulher,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adulto,Econômica,Terceira Classe
3,4,Sim,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mulher,35.0,1,0,113803,53.1000,C123,S,Adulto,Premium,Primeira Classe
4,5,Não,3,"Allen, Mr. William Henry",Homem,35.0,0,0,373450,8.0500,NaN,S,Adulto,Econômica,Terceira Classe
5,6,Não,3,"Moran, Mr. James",Homem,NaN,0,0,330877,8.4583,NaN,Q,Idoso,Econômica,Terceira Classe
6,7,Não,1,"McCarthy, Mr. Timothy J",Homem,54.0,0,0,17463,51.8625,E46,S,Adulto,Premium,Primeira Classe
7,8,Não,3,"Palsson, Master. Gosta Leonard",Homem,2.0,3,1,349909,21.0750,NaN,S,Menor,Intermediário,Terceira Classe
8,9,Sim,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Mulher,27.0,0,2,347742,11.1333,NaN,S,Adulto,Econômica,Terceira Classe
9,10,Sim,2,"Nasser, Mrs. Nicholas (Adele Achem)",Mulher,14.0,1,0,237736,30.0708,NaN,C,Menor,Intermediário,Segunda Classe

### 1.6.5 - Criação de colunas com apply()
O apply() é usado quando a lógica é complexa demais para vetorização simples.

👉 Primeiro ponto importante
- Criação vetorizada (preferencial)
`df['Adulto'] = df['Age'] >= 18` **ou** `np.where(...)` normalmente são mais rápidos.

Mas às vezes precisamos de lógica mais rica
- múltiplas regras
- dependência entre colunas
- decisões customizadas

Aí usamos: `apply(axis=1)`

**Exemplo:**
```
def categoria(row):

    if row['Age'] < 18:
        return 'Menor'

    elif row['Fare'] > 100:
        return 'VIP'

    else:
        return 'Adulto'
```

**Aplicando:**

`df['Categoria'] = df.apply(categoria, axis=1)`


**O que acontece?**

O Pandas:
- pega uma linha
- transforma em Series
- envia para função
- recebe retorno
- monta nova coluna

⚠️ ALERTA MAIS IMPORTANTE

O apply(axis=1) costuma ser lento.

Porque:
- passa linha por linha
- executa Python repetidamente
- perde otimização vetorial

🧠 Regra profissional

Antes de usar `apply(axis=1)`, pergunte: “consigo resolver isso com
- vetorização?
- np.where?
- np.select?
- map? "

Porque geralmente essas opções são:
- mais rápidas
- mais idiomáticas
- mais escaláveis


**Resumindo:**

O `apply()` não é “a solução padrão” e sim “o plano B quando vetorização não resolve elegantemente”

### 1.6.6 - Diferenças de performance

A ideia central é :
- operações vetorizadas usam código otimizado em baixo nível.
- `apply()` frequentemente executa Python repetidamente.

✔️ Vetorizado: `df['Age'] + 10`

❌ apply() : `df['Age'].apply(lambda x: x + 10)`

Ambos fazem a mesma coisa, mas Mas internamente são MUITO diferentes:

**Vetorização**

O NumPy:
- trabalha em arrays contínuos
- usa operações em C
- aproveita CPU otimizada

Resultado: Muito rápido

**apply()**

O Pandas:
- pega elemento
- chama função Python
- executa
- repete milhares/milhões de vezes

Resultado: Muito mais overhead

⚡ E a diferença de performance pode ser absurda.

Em datasets grandes:
- segundos
- minutos
- até horas

🔥 Ordem geral de performance
🥇 Mais rápido
```
- operações vetorizadas
+
-
*
/
comparações
str
dt
```
🥈 Médio

`map(), replace()`

🥉 Mais lento

`apply()`

💀 Mais lento ainda

loops explícitos (for)

**Regra profissional IMPORTANTÍSSIMA**

| Tentativa | Ferramenta               |
| --------- | ------------------------ |
| 1         | vetorização              |
| 2         | `np.where` / `np.select` |
| 3         | `map`                    |
| 4         | `apply`                  |
| 5         | loop manual              |

🔥 E aqui está a grande verdade

- Muita gente aprende Pandas assim: “como fazer funcionar”
- Mas o correto é: “como fazer de forma vetorizada?”

**Resumindo:**

❌ Mentalidade Excel : linha por linha

✔️ Mentalidade Pandas : operações sobre vetores

**Insight importante**

O Pandas foi construído para: processamento vetorial

O apply() existe:
- como flexibilidade
- não como caminho principal

| Método            | Performance | Estilo                 |
| ----------------- | ----------- | ---------------------- |
| vetorização       | 🔥🔥🔥      | idiomático             |
| `np.where/select` | 🔥🔥        | condicional vetorizado |
| `map()`           | 🔥🔥        | transformação simples  |
| `apply()`         | 🔥          | flexível               |
| `for`             | 💀          | anti-Pandas            |

## 1.7 - Groupyby()
Se criação de colunas é **transformação** , o `groupby()` é **análise**

##### **O que é groupby()?**
O groupby() é um método que divide os dados em grupos e aplica operações em cada grupo.

**Lógica**

dividir → aplicar → combinar

Exemmplo: `df.groupby('Pclass')['Age'].mean()`

**O que isso faz?**
1. Divide por Pclass
2. Aplica o `mean()` na coluna Age
3. Combina o resultado final por grupo

**Saída**

| Pclass | Idade média |
| ------ | ----------- |
| 1      | 38          |
| 2      | 29          |
| 3      | 24          |


**Exemplos reais**
- vendas por região
- salário por departamento
- média por categoria
- churn por cliente
- receita por produto


🚀 Sequência de aprendizado

1️⃣ Fundamentos do groupby
- sintaxe
- objeto GroupBy
- agregações

2️⃣ Agregações
- mean
- sum
- count
- nunique
- agg

3️⃣ Agrupamentos múltiplos
- groupby(['Sex', 'Pclass'])

4️⃣ agg() — MUITO importante

- Múltiplas métricas ao mesmo tempo.

5️⃣ transform()

- (um dos tópicos mais difíceis e poderosos)

6️⃣ Diferença entre:
- agg
- apply
- transform

**Documentação:** https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

In [43]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

### 1.7.1 - Fundamentos do Groupby()

**Princípios**

**Groupby**: a ideia desse método é dividir os dados em grupos com base nos critérios selecionados e em seguida, aplicar uma operação a esses grupos
Esse método possui diversos parâmetros, sendo os principais:


**by**: especifica a coluna ou colunas que desejamos agrupar. Como argumento podemos passar o nome de uma coluna oou uma lista com os nomes das colunas


**axis**: especifica o eixo ao longo do qual(is) desejamos agrupar. O valor padrão é 0. O que siginifica que as linhas serão agrupadas. Se quisermos agrupar a colunas, devemos especificar axis = 1.


**sort**: parâmetro booleano( True ou False) que indica se os grupos devem ser ordenados de maneira ascendente ou descendentes. o valor padrão é True.


**dropna**:  utilizamos o dropana para controlar se os valores nulos ( NaN) serão mantidos ou excluídos durante o processo de agrupamento. o padrão é True.

**Mentalidade correta:** dividir → aplicar → combinar

In [44]:
df.groupby('Pclass')['Age'].mean()
 #“agruppe os passageiros por classe e calcule a média da idade em cada grupo”

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

**O que acontece internamente?**

1️⃣ Divide

O Pandas separa:
```
Pclass = 1
Pclass = 2
Pclass = 3
```

2️⃣ Aplicação

Para cada grupo o `mean()` na coluna **Age**

3️⃣ Combina

Resultado final:

|Pclass|Age|
|-----|----|
|1|38.2|
|2|29.8|
|3|24.5|

<br/>

👉 **Atenção:**

O groupby() NÃO executa imediatamente. Quando fazemos `df.groupby('Pclass')`, o Pandas retorna `<GroupBy object>`

Isso significa que o agrupamento foi definido, mas não foi executado

**Pense assim**: `df.groupby('Pclass')` significa “prepare os grupos”

Só depois você diz O QUE fazer: `.mean()` , `.sum()` ou `.count()`

**Então o fluxo correto é:** df.groupby(...).alguma_operacao()
```
grupo = df.groupby('Pclass')

type(grupo)

```
O GroupBy é:

- um objeto intermediário
- especializado em operações agrupadas

Agora entram as agregações. As mais importantes são:

| Método      | Função          |
| ----------- | --------------- |
| `mean()`    | média           |
| `sum()`     | soma            |
| `count()`   | conta não nulos |
| `size()`    | conta linhas    |
| `min()`     | mínimo          |
| `max()`     | máximo          |
| `nunique()` | valores únicos  |

In [45]:
# alterarei novamente a coluna Survived para podermos calcular a média
df['Survived']= df['Survived'].replace({
    'Sim': 1,
    'Não': 0
})

/tmp/ipykernel_3078/9480994.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Survived']= df['Survived'].replace({

In [46]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

###***Notas***

####**count() vs size()**

**count():**:  conta valores NÃO nulos

**size()**: conta linhas totais

Exemplo:
Se Age possui NaN, então `df.groupby('Pclass')['Age'].count()` ignora os NaN.
Mas `df.groupby('Pclass').size()` conta tudo

#### 1.7.1.1 - O objeto GroupBy

Quando você faz `grupo = df.groupby('Pclass')

o Pandas NÃO retorna DataFrame, Series ou lista. Ele retorna um  objeto GroupBy

**Isso significa que :** o Pandas:
- organizou os grupos internamente
- mas ainda NÃO executou cálculo algum

Representação visutal do objeto Groupby
```
Classe 1 → índices [1, 3, 6, 10]
Classe 2 → índices [0, 4, 8]
Classe 3 → índices [2, 5, 7]
```

⚠️ Importante

Ele NÃO cria vários DataFrames separados imediatamente pois isso seria:

- pesado
- lento
- ruim para memória

In [47]:
grupo = df.groupby('Pclass')

type(grupo)

pandas.core.groupby.generic.DataFrameGroupBy

E agora vem algo MUITO importante: O GroupBy é ***lazy-ish***(“semi preguiçoso")

**🧠 O que isso quer dizer?**

O Pandas adia operações até você pedir uma agregação

**Exemplo:** `grupo.count()`

In [48]:
grupo.count()
#note que os valores não são os mesmos para todas as colunas. O motivo é da diveferença de grupos
# a contagem no campo idade, por exemplo não faz sentido, visto que a idade é um número

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa,ClasseNome
Pclass,,,,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214,216,216,216
2,184,184,184,184,173,184,184,184,184,16,184,184,184,184
3,491,491,491,491,355,491,491,491,491,12,491,491,491,491

In [49]:
#retornar colunas específicas
grupo[['Pclass','Age']].count()
#observação: esse é apenas um exemplo didático, mas sem saber o que significa cada coluna, podemos ter resultados discrepantes.

        Pclass  Age
Pclass
1          216  186
2          184  173
3          491  355

In [50]:
idade = df.groupby('Pclass')
idade[['Age']].mean()
#Agora temos a idade média por classe, o que faz mais sentido que o retorno acima

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

Isso é MUITO poderoso porque permit `df.groupby(...)[...].agg(...)`em em pipelines eficientes.

**Explorando o GroupBy**

Podemos checar quais dados foram agrupados em cada grupo com o uso do atributo groups  e realizar seleções de grupos específicos com o método get_group()

`grupo.groups`
```
{
    1: [1, 3, 6],
    2: [0, 4],
    3: [2, 5]
}
```

In [51]:
grupo.groups

{1: [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 2: [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 3: [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [52]:
#ver um grupo específico
grupo.get_group(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa,ClasseNome
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mulher,38.0,1,0,PC 17599,71.2833,C85,C,Adulto,Premium,Primeira Classe
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mulher,35.0,1,0,113803,53.1000,C123,S,Adulto,Premium,Primeira Classe
6,7,0,1,"McCarthy, Mr. Timothy J",Homem,54.0,0,0,17463,51.8625,E46,S,Adulto,Premium,Primeira Classe
11,12,1,1,"Bonnell, Miss. Elizabeth",Mulher,58.0,0,0,113783,26.5500,C103,S,Adulto,Intermediário,Primeira Classe
23,24,1,1,"Sloper, Mr. William Thompson",Homem,28.0,0,0,113788,35.5000,A6,S,Adulto,Intermediário,Primeira Classe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",Mulher,47.0,1,1,11751,52.5542,D35,S,Adulto,Premium,Primeira Classe
872,873,0,1,"Carlsson, Mr. Frans Olof",Homem,33.0,0,0,695,5.0000,B51 B53 B55,S,Adulto,Econômica,Primeira Classe
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",Mulher,56.0,0,1,11767,83.1583,C50,C,Adulto,Premium,Primeira Classe
887,888,1,1,"Graham, Miss. Margaret Edith",Mulher,19.0,0,0,112053,30.0000,B42,S,Adulto,Intermediário,Primeira Classe
889,890,1,1,"Behr, Mr. Karl Howell",Homem,26.0,0,0,111369,30.0000,C148,C,Adulto,Intermediário,Primeira Classe

**Iterando Grupos**

| Variável | Representa         |
| -------- | ------------------ |
| `nome`   | valor do grupo     |
| `dados`  | DataFrame do grupo |

In [53]:
for nome, dados in grupo:
    print(nome)
    print(dados.head())

1
    PassengerId  Survived  Pclass  \
1             2         1       1
3             4         1       1
6             7         0       1
11           12         1       1
23           24         1       1

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  Mulher  38.0      1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  Mulher  35.0      1
6                             McCarthy, Mr. Timothy J   Homem  54.0      0
11                           Bonnell, Miss. Elizabeth  Mulher  58.0      0
23                       Sloper, Mr. William Thompson   Homem  28.0      0

    Parch    Ticket     Fare Cabin Embarked FaixaEtaria CategoriaTarifa  \
1       0  PC 17599  71.2833   C85        C      Adulto         Premium
3       0    113803  53.1000  C123        S      Adulto         Premium
6       0     17463  51.8625   E46        S      Adulto         Premium
11      0    113783  26.5500  C103        S      Adulto   Intermediário
23      0    113788  35.5000    A6        S      Adulto   Intermediário

         ClasseNome
1   Primeira Classe
3   Primeira Classe
6   Primeira Classe
11  Primeira Classe
23  Primeira Classe
2
    PassengerId  Survived  Pclass                                 Name  \
9            10         1       2  Nasser, Mrs. Nicholas (Adele Achem)
15           16         1       2     Hewlett, Mrs. (Mary D Kingcome)
17           18         1       2         Williams, Mr. Charles Eugene
20           21         0       2                 Fynney, Mr. Joseph J
21           22         1       2                Beesley, Mr. Lawrence

       Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked FaixaEtaria  \
9   Mulher  14.0      1      0  237736  30.0708   NaN        C       Menor
15  Mulher  55.0      0      0  248706  16.0000   NaN        S      Adulto
17   Homem   NaN      0      0  244373  13.0000   NaN        S       Idoso
20   Homem  35.0      0      0  239865  26.0000   NaN        S      Adulto
21   Homem  34.0      0      0  248698  13.0000   D56        S      Adulto

   CategoriaTarifa      ClasseNome
9    Intermediário  Segunda Classe
15       Econômica  Segunda Classe
17       Econômica  Segunda Classe
20   Intermediário  Segunda Classe
21       Econômica  Segunda Classe
3
   PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris   Homem
2            3         1       3          Heikkinen, Miss. Laina  Mulher
4            5         0       3        Allen, Mr. William Henry   Homem
5            6         0       3                Moran, Mr. James   Homem
7            8         0       3  Palsson, Master. Gosta Leonard   Homem

    Age  SibSp  Parch            Ticket     Fare Cabin Embarked FaixaEtaria  \
0  22.0      1      0         A/5 21171   7.2500   NaN        S      Adulto
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S      Adulto
4  35.0      0      0            373450   8.0500   NaN        S      Adulto
5   NaN      0      0            330877   8.4583   NaN        Q       Idoso
7   2.0      3      1            349909  21.0750   NaN        S       Menor

  CategoriaTarifa       ClasseNome
0       Econômica  Terceira Classe
2       Econômica  Terceira Classe
4       Econômica  Terceira Classe
5       Econômica  Terceira Classe
7   Intermediário  Terceira Classe

⚠️ Agora vem um insight MUITO importante

O groupby() cria uma abstração sobre:

- separação lógica
- não necessariamente separação física imediata

Isso ajuda na performance, otimização do uso da memória e flexibilidade

**Considerações finais**
Existe um detalhe MUITO importante sobre groupby() que costuma causar confusão no começo: o índice

`df.groupby('Pclass')['Age'].mean()`
```
Pclass
1    38.2
2    29.8
3    24.5
```

A coluna **Pclass** virou o índice.

Isso acontece porque o groupby() usa naturalmente as chaves do agrupamento como índice.

para contornar isso, usamos as_index=False.

Veja os  exemplos abaixo

In [54]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [55]:
df.groupby('Pclass', as_index=False)['Age'].mean()

   Pclass        Age
0       1  38.233441
1       2  29.877630
2       3  25.140620

⚠️ Isso é MUITO usado

Especialmente quando:
- você quer exportar
- juntar tabelas (merge)
- trabalhar estilo SQL

⚠️ Outro detalhe importante
**Agrupamento múltiplo**
Exemplo: `df.groupby(['Sex', 'Pclass'])['Fare'].mean()`
```

Sex     Pclass
female  1         106
        2          21
male    1          67
```

⚠️ Isso é MUITO importante no Pandas
O índice pode virar hierárquico e multidimensional

Você pode:

- navegar grupos
- reorganizar índice
- usar unstack()
- fazer tabelas analíticas

🧠 Outro conceito importante
GroupBy NÃO altera o DataFrame original

Ele retorna:
- nova estrutura
- nova agregação

🔥 E talvez o insight mais importante de todos: o groupby() é uma operação de REDUÇÃO. Isso significa que você sair de 890 linhas para 3 linhas

**Resumo:**

| Conceito         | Ideia                        |
| ---------------- | ---------------------------- |
| `GroupBy`        | estrutura de agrupamento     |
| agregação        | redução dos dados            |
| `as_index=False` | resultado estilo tabela      |
| múltiplos grupos | MultiIndex                   |
| `groupby()`      | dividir → agregar → combinar |

In [56]:
df.groupby(['Sex', 'Pclass'])['Fare'].mean()

Sex     Pclass
Homem   1          67.226127
        2          19.741782
        3          12.661633
Mulher  1         106.125798
        2          21.970121
        3          16.118810
Name: Fare, dtype: float64

In [57]:
df.groupby(['Sex', 'Pclass'], as_index=False)['Fare'].mean()

      Sex  Pclass        Fare
0   Homem       1   67.226127
1   Homem       2   19.741782
2   Homem       3   12.661633
3  Mulher       1  106.125798
4  Mulher       2   21.970121
5  Mulher       3   16.118810

In [58]:
#opção muito comum no mercado e funciona igual a anterior
df.groupby(['Sex', 'Pclass'])['Fare'].mean().reset_index()

      Sex  Pclass        Fare
0   Homem       1   67.226127
1   Homem       2   19.741782
2   Homem       3   12.661633
3  Mulher       1  106.125798
4  Mulher       2   21.970121
5  Mulher       3   16.118810

**comparação**

***as_index=False***:direto

Evita criar MultiIndex desde o começo.

`df.groupby('Pclass', as_index=False)['Fare'].mean()`


**reset_index()**: Mais flexível

Porque você pode:
- trabalhar com índice hierárquico primeiro
- reorganizar depois

🔥 E aqui vem um detalhe MUITO importante

Nem toda operação aceita `as_index=False`. Então o `reset_index()` continua sendo ferramenta essencial.

O `as_index=False` é um parâmetro do groupby(), mas ele funciona principalmente em operações de agregação que retornam DataFrames “reduzidos”.

Ele funciona muito bem com:
- mean
- sum
- agg
- count

Mas perde efeito — ou nem faz sentido — em algumas operações mais complexas.

**Exemplo:**
```
df.groupby('Pclass', as_index=False).apply(
    lambda x: x.head(2)
)
```
Aqui o resultado pode:
- manter índice hierárquico
- criar MultiIndex mesmo assim
- ignorar parcialmente o efeito esperado

⚠️ Porque apply() é muito mais livre

Ele pode retornar:

- DataFrame
- Series
- escalar
- estrutura arbitrária

Então o Pandas nem sempre consegue manter formato “tabular simples”.

### 7.1.3 - Agregações
Aqui o Pandas começa a responder perguntas analíticas reais.

O que é uma agregação?

Uma agregaçãoreduz vários valores em um único resultado.

**Exemplo simples**

idade = [22, 35,18,40]

media = 28.75

| Método      | Função          |
| ----------- | --------------- |
| `mean()`    | média           |
| `sum()`     | soma            |
| `min()`     | mínimo          |
| `max()`     | máximo          |
| `count()`   | não nulos       |
| `size()`    | total de linhas |
| `median()`  | mediana         |
| `std()`     | desvio padrão   |
| `nunique()` | valores únicos  |

In [59]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

⚠️ Lembre-se:
 O count() ignora o NaN e o size() conta todas as linhas

In [60]:
df.groupby('Pclass')['Age'].count()

Pclass
1    186
2    173
3    355
Name: Age, dtype: int64

In [61]:
df.groupby('Pclass')['Age'].size()

Pclass
1    216
2    184
3    491
Name: Age, dtype: int64

#### 7.1.3.1 -  AGG()

O agg() é provavelmente uma das ferramentas mais importantes do groupby().
Porque ele permite:
- várias métricas
- várias colunas
- tudo em uma única operação

Antes do `agg()` faríamos:

-  → `df.groupby('Pclass')['Fare'].mean()`
-  → `df.groupby('Pclass')['Fare'].max()`
-  → `df.groupby('Pclass')['Fare'].min()`

Isso é repetitivo e ineficiente

**Com o Agg()**
```
df.groupby('Pclass')['Fare'].agg(
    ['mean', 'max', 'min']
)
```

**Documentação:** https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html

In [62]:

df.groupby('Pclass')['Fare'].agg(
    ['mean', 'max', 'min']
)

             mean       max  min
Pclass
1       84.154687  512.3292  0.0
2       20.662183   73.5000  0.0
3       13.675550   69.5500  0.0

In [63]:
df.groupby('Pclass').agg({
    'Age': 'mean',
    'Fare': 'sum',
    'PassengerId': 'count'
})

              Age        Fare  PassengerId
Pclass
1       38.233441  18177.4125          216
2       29.877630   3801.8417          184
3       25.140620   6714.6951          491

```
df.groupby('Pclass').agg({
    'Age': 'mean',
    'Fare': 'sum',
    'PassengerId': 'count'
})
```
| Coluna      | Operação |
| ----------- | -------- |
| Age         | média    |
| Fare        | soma     |
| PassengerId | contagem |

In [64]:
df.groupby('Pclass', as_index=False).agg({
    'Age': 'mean',
    'Fare': 'sum',
    'PassengerId': 'count'
})

   Pclass        Age        Fare  PassengerId
0       1  38.233441  18177.4125          216
1       2  29.877630   3801.8417          184
2       3  25.140620   6714.6951          491

E aqui vem uma técnica MUITO usada
***Nomeando agregações***
```
df.groupby('Pclass').agg(
    media_idade = ('Age', 'mean'),
    maior_tarifa = ('Fare', 'max'),
    total = ('PassengerId', 'count')
)
```

🚀 E aqui começa o Pandas realmente analítico

Você passa a construir:
- tabelas resumo
- KPIs
- estatísticas agrupadas
- visões executivas

com pouquíssimo código.

In [65]:
df.groupby('Pclass').agg(
    media_idade = ('Age', 'mean'),
    maior_tarifa = ('Fare', 'max'),
    total = ('PassengerId', 'count')
)

        media_idade  maior_tarifa  total
Pclass
1         38.233441      512.3292    216
2         29.877630       73.5000    184
3         25.140620       69.5500    491

**Considerações Finais**
O agg() é uma interface genérica de agregação pois ele aceita diferentes tipos de agregadores.

Já vimos o 'mean', 'max' e o 'sum'. Mas também podemos usar:
- funções de string como `df.groupby('Pclass')['Fare'].agg(len)`
- funções do **Numpy**
- funções personalizadas

🚀 Outro detalhe MUITO importante

Agregações múltiplas geram DataFrame
- `df.groupby('Pclass')['Fare'].mean()` → Serie
- `df.groupby('Pclass')['Fare'].agg( ['mean', 'max'])` → DataFrame

In [66]:
df.groupby('Pclass')['Fare'].agg(len)

Pclass
1    216
2    184
3    491
Name: Fare, dtype: int64

In [67]:
import numpy as np

df.groupby('Pclass')['Fare'].agg(np.mean)

/tmp/ipykernel_3078/2045260603.py:3: FutureWarning: The provided callable <function mean at 0x7f2dc95398a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('Pclass')['Fare'].agg(np.mean)

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [68]:
def amplitude(x):
    return x.max() - x.min()

In [69]:
df.groupby('Pclass')['Fare'].agg(amplitude)

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [70]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [71]:
type(df.groupby('Pclass')['Fare'].mean())

pandas.core.series.Series

In [72]:
df.groupby('Pclass')['Fare'].agg(
    ['mean', 'max']
)

             mean       max
Pclass
1       84.154687  512.3292
2       20.662183   73.5000
3       13.675550   69.5500

In [73]:
type(df.groupby('Pclass')['Fare'].agg(
    ['mean', 'max']
))

pandas.core.frame.DataFrame

### 7.1.4 - transform()

O método transform() permite executar uma função para cada valor do DataFrame.

**sintaxe**

dataframe.transform(func, axis, raw, result_type, args, kwds)

**No entanto**, ele devolve resultado no tamanho original do DataFrame.

**Comparação**
- df.groupby('Pclass')['Fare'].mean()

    | Pclass | Fare |
    | ------ | ---- |
    | 1      | 84   |
    | 2      | 20   |
    | 3      | 13   |

  890 linhas → 3 grupos

- df.groupby('Pclass')['Fare'].transform('mean')
  Saída: Uma Series com 890 linhas
  Exemplo
  | Passenger | Pclass | Fare | Transform mean |
  | --------- | ------ | ---- | -------------- |
  | A         | 1      | 80   | 84             |
  | B         | 1      | 100  | 84             |
  | C         | 2      | 20   | 20             |

**O que aconteceu?**
Cada passageiro recebeu a média da sua própria classe

🔥Vantagens

- comparar indivíduo vs grupo
- criar métricas contextuais
- fazer feature engineering

In [74]:
df['Fare_Diff'] = (
    df['Fare']
    - df.groupby('Pclass')['Fare'].transform('mean')
)

In [75]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa,ClasseNome,Fare_Diff
0,1,0,3,"Braund, Mr. Owen Harris",Homem,22.0,1,0,A/5 21171,7.2500,NaN,S,Adulto,Econômica,Terceira Classe,-6.425550
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mulher,38.0,1,0,PC 17599,71.2833,C85,C,Adulto,Premium,Primeira Classe,-12.871387
2,3,1,3,"Heikkinen, Miss. Laina",Mulher,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adulto,Econômica,Terceira Classe,-5.750550
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mulher,35.0,1,0,113803,53.1000,C123,S,Adulto,Premium,Primeira Classe,-31.054687
4,5,0,3,"Allen, Mr. William Henry",Homem,35.0,0,0,373450,8.0500,NaN,S,Adulto,Econômica,Terceira Classe,-5.625550
5,6,0,3,"Moran, Mr. James",Homem,NaN,0,0,330877,8.4583,NaN,Q,Idoso,Econômica,Terceira Classe,-5.217250
6,7,0,1,"McCarthy, Mr. Timothy J",Homem,54.0,0,0,17463,51.8625,E46,S,Adulto,Premium,Primeira Classe,-32.292187
7,8,0,3,"Palsson, Master. Gosta Leonard",Homem,2.0,3,1,349909,21.0750,NaN,S,Menor,Intermediário,Terceira Classe,7.399450
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Mulher,27.0,0,2,347742,11.1333,NaN,S,Adulto,Econômica,Terceira Classe,-2.542250
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Mulher,14.0,1,0,237736,30.0708,NaN,C,Menor,Intermediário,Segunda Classe,9.408617

Isso é MUITO usado em:
- machine learning
- detecção de outliers
- análise contextual
- normalização

⚠️ Insight MAIS importante

O transform() NÃO reduz.
| Método        | Retorno                 |
| ------------- | ----------------------- |
| `agg()`       | reduz grupos            |
| `transform()` | mantém tamanho original |
| `apply()`     | flexível                |

In [76]:
df['Percentual'] = (
    df['Fare']
    / df.groupby('Pclass')['Fare'].transform('sum')
)

In [77]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa,ClasseNome,Fare_Diff,Percentual
0,1,0,3,"Braund, Mr. Owen Harris",Homem,22.0,1,0,A/5 21171,7.2500,NaN,S,Adulto,Econômica,Terceira Classe,-6.425550,0.001080
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mulher,38.0,1,0,PC 17599,71.2833,C85,C,Adulto,Premium,Primeira Classe,-12.871387,0.003922
2,3,1,3,"Heikkinen, Miss. Laina",Mulher,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adulto,Econômica,Terceira Classe,-5.750550,0.001180
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mulher,35.0,1,0,113803,53.1000,C123,S,Adulto,Premium,Primeira Classe,-31.054687,0.002921
4,5,0,3,"Allen, Mr. William Henry",Homem,35.0,0,0,373450,8.0500,NaN,S,Adulto,Econômica,Terceira Classe,-5.625550,0.001199
5,6,0,3,"Moran, Mr. James",Homem,NaN,0,0,330877,8.4583,NaN,Q,Idoso,Econômica,Terceira Classe,-5.217250,0.001260
6,7,0,1,"McCarthy, Mr. Timothy J",Homem,54.0,0,0,17463,51.8625,E46,S,Adulto,Premium,Primeira Classe,-32.292187,0.002853
7,8,0,3,"Palsson, Master. Gosta Leonard",Homem,2.0,3,1,349909,21.0750,NaN,S,Menor,Intermediário,Terceira Classe,7.399450,0.003139
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Mulher,27.0,0,2,347742,11.1333,NaN,S,Adulto,Econômica,Terceira Classe,-2.542250,0.001658
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Mulher,14.0,1,0,237736,30.0708,NaN,C,Menor,Intermediário,Segunda Classe,9.408617,0.007910

In [78]:
#Padronização do Z-Score

df['Age_ZScore'] = (
    (
        df['Age']
        - df.groupby('Pclass')['Age'].transform('mean')
    )
    /
    df.groupby('Pclass')['Age'].transform('std')
)

In [79]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FaixaEtaria,CategoriaTarifa,ClasseNome,Fare_Diff,Percentual,Age_ZScore
0,1,0,3,"Braund, Mr. Owen Harris",Homem,22.0,1,0,A/5 21171,7.2500,NaN,S,Adulto,Econômica,Terceira Classe,-6.425550,0.001080,-0.251342
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mulher,38.0,1,0,PC 17599,71.2833,C85,C,Adulto,Premium,Primeira Classe,-12.871387,0.003922,-0.015770
2,3,1,3,"Heikkinen, Miss. Laina",Mulher,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adulto,Econômica,Terceira Classe,-5.750550,0.001180,0.068776
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mulher,35.0,1,0,113803,53.1000,C123,S,Adulto,Premium,Primeira Classe,-31.054687,0.002921,-0.218434
4,5,0,3,"Allen, Mr. William Henry",Homem,35.0,0,0,373450,8.0500,NaN,S,Adulto,Econômica,Terceira Classe,-5.625550,0.001199,0.789041
5,6,0,3,"Moran, Mr. James",Homem,NaN,0,0,330877,8.4583,NaN,Q,Idoso,Econômica,Terceira Classe,-5.217250,0.001260,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",Homem,54.0,0,0,17463,51.8625,E46,S,Adulto,Premium,Primeira Classe,-32.292187,0.002853,1.065103
7,8,0,3,"Palsson, Master. Gosta Leonard",Homem,2.0,3,1,349909,21.0750,NaN,S,Menor,Intermediário,Terceira Classe,7.399450,0.003139,-1.851931
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Mulher,27.0,0,2,347742,11.1333,NaN,S,Adulto,Econômica,Terceira Classe,-2.542250,0.001658,0.148805
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Mulher,14.0,1,0,237736,30.0708,NaN,C,Menor,Intermediário,Segunda Classe,9.408617,0.007910,-1.134029


### 7.1.5 - Diferença entre: agg() , apply() e transform()

O transform() exige mesmo tamanho de saída do grupo

**Exemplo válido**

Grupo  [10, 20, 30] → Retorno: [20, 20, 20]

**Exemplo inválido**

Grupo  [10, 20, 30] → Retorno: [20]

E aqui nasce a diferença fundamental

| Método        | Objetivo                     |
| ------------- | ---------------------------- |
| `agg()`       | resumir grupo                |
| `transform()` | propagar informação do grupo |
| `apply()`     | flexibilidade total          |

## 7.2 - Pivot Table ( tabelas dinâmicas)

Com o pivot_table() o Pandas começa a ficar MUITO próximo de:
- tabela dinâmica do Excel
- cubos analíticos
- BI


Enquanto o **groupby()** foca em agregar, o **pivot_table()** foca em organizar visualmente os agregados.

Exemplo:

| Sex    | 1ª Classe | 2ª Classe | 3ª Classe |
| ------ | --------- | --------- | --------- |
| female | 0.96      | 0.92      | 0.50      |
| male   | 0.40      | 0.15      | 0.13      |


| Parâmetro | Significa      |
| --------- | -------------- |
| `values`  | o que calcular |
| `index`   | linhas         |
| `columns` | colunas        |
| `aggfunc` | agregação      |


**Documentação:** https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html

In [80]:
df.pivot_table(
    values='Survived',
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
)

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000


# Parte 2 - Pandas  avançado
Nessa sessão, estudaremos os seguintes tópicos

Próximos tópicos:
- reshaping
- MultiIndex
- visualização analítica
- cruzamento de dimensões
- tabelas matriciais

## 2.1 Tipos de dataframe

O **reshaping** consite em alterar o formato do dataframe

Os datasets podemos ser divididos em dois tipos: wide e long:

**Wide:** também conhecidos como tabelas pivô. Nesse tipo de tabela , há uma única linha de cabeçalho que contém diversas colunas , geralmente mais colunas do que linhas. Esse tipo de tabela são úteis para armazenar informações que possuem muitos atributos como formulários de pesquisa. As colunas podem conter valores ausentes para células em que os dados não se aplicam.

**Exemplo:**
|Nível - Setor|2017|2018|2019|
|-------------|----|----|----|
|Processos industriais|897.6|758.0|902.0|
|Processos Industriais|130.0|168.0|98.0|
|Mudança de uso da Terra|378.03|388.09|935.0|

**Long:** também conhecido como formato normativo ou estreito. As tabelas nesse formato armazenam cada observação em uma linha ao invés de uma linha de cabeçalho contendo todas as colunas.
As tabelas no formato long geralmente tem duas colunas principais de informação. Uma para o nome das variáveis e outra para o valor das variáveis.
São úteis para o armazenamento de informações com muitas observações como séries temporais ou dados de experimentos científicos.

**Exemplo:**
|Nível - Setor|Ano|Emissão|
|-------------|---|-------|
|Processos industriais|2017|897.6|
|Processos Industriais|2018|758.0|
|Mudança de uso da Terra|2017|378.03|
|Processos industriais|2018|902.0|

> Fonte: Formação Pandas Alura ( anotações do aluno)

Os pilares do reshaping são

| Operação        | Ideia             |
| --------------- | ----------------- |
| `pivot()`       | linhas → colunas  |
| `pivot_table()` | pivot + agregação |
| `melt()`        | colunas → linhas  |
| `stack()`       | colunas → índice  |
| `unstack()`     | índice → colunas  |

### 2.1.1 Alterando o formado do DataFrame
| Operação        | Transformação           |
| --------------- | ----------------------- |
| `melt()`        | wide → long             |
| `pivot()`       | long → wide             |
| `pivot_table()` | long → wide + agregação |
| `stack()`       | colunas → índice        |
| `unstack()`     | índice → colunas        |

#### 2.1.1.1 melt()

o melt() transforma colunas em linhas

In [81]:
df.pivot_table(
    values='Survived',
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
)

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

**O que isso faz? **

| Parâmetro           | Significado    |
| ------------------- | -------------- |
| `values='Survived'` | o que calcular |
| `index='Sex'`       | linhas         |
| `columns='Pclass'`  | colunas        |
| `aggfunc='mean'`    | média          |

#### 2.1.1.2 Aplicando o melt()

In [82]:
mini_df = df[
    ['PassengerId', 'Age', 'Fare']
]

In [83]:
mini_df.head()

   PassengerId   Age     Fare
0            1  22.0   7.2500
1            2  38.0  71.2833
2            3  26.0   7.9250
3            4  35.0  53.1000
4            5  35.0   8.0500

In [84]:
mini_df.melt(
    id_vars='PassengerId',
    var_name='Variavel',
    value_name='Valor'
)

      PassengerId Variavel  Valor
0               1      Age  22.00
1               2      Age  38.00
2               3      Age  26.00
3               4      Age  35.00
4               5      Age  35.00
...           ...      ...    ...
1777          887     Fare  13.00
1778          888     Fare  30.00
1779          889     Fare  23.45
1780          890     Fare  30.00
1781          891     Fare   7.75

[1782 rows x 3 columns]

Para transfomarmos um Datraframe do formato long para wide, usamos o pivot

In [85]:
sobrevivencia = (
    df.groupby(
        ['Sex', 'Pclass']
    )['Survived']
    .mean()
    .reset_index()
)
sobrevivencia

      Sex  Pclass  Survived
0   Homem       1  0.368852
1   Homem       2  0.157407
2   Homem       3  0.135447
3  Mulher       1  0.968085
4  Mulher       2  0.921053
5  Mulher       3  0.500000

In [86]:
sobrevivencia.pivot(
    index='Sex',
    columns='Pclass',
    values='Survived'
)

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

***Resumo***

| Ferramenta    | Objetivo                          |
| ------------- | --------------------------------- |
| `groupby`     | resumir                           |
| `pivot_table` | resumir + reorganizar visualmente |
| `melt`        | normalizar estrutura              |

### 2.1.2 - stack() e unstack()

| Método      | Transforma       |
| ----------- | ---------------- |
| `stack()`   | colunas → índice |
| `unstack()` | índice → colunas |

In [87]:
tabela = df.pivot_table(
    values='Survived',
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
)

tabela

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

In [88]:
tabela.stack()
#multi-index

Sex     Pclass
Homem   1         0.368852
        2         0.157407
        3         0.135447
Mulher  1         0.968085
        2         0.921053
        3         0.500000
dtype: float64

In [89]:
tabela.stack().reset_index()

      Sex  Pclass         0
0   Homem       1  0.368852
1   Homem       2  0.157407
2   Homem       3  0.135447
3  Mulher       1  0.968085
4  Mulher       2  0.921053
5  Mulher       3  0.500000

In [90]:

## Criará uma dataframe multi-index
grupo = (
    df.groupby(
        ['Sex', 'Pclass']
    )['Survived']
    .mean()
)

grupo

Sex     Pclass
Homem   1         0.368852
        2         0.157407
        3         0.135447
Mulher  1         0.968085
        2         0.921053
        3         0.500000
Name: Survived, dtype: float64

**Controlando o índice**

In [91]:
grupo.unstack()

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

In [92]:
grupo.unstack(level=0)

Sex        Homem    Mulher
Pclass
1       0.368852  0.968085
2       0.157407  0.921053
3       0.135447  0.500000

In [93]:
grupo.unstack(level='Sex')

Sex        Homem    Mulher
Pclass
1       0.368852  0.968085
2       0.157407  0.921053
3       0.135447  0.500000

**Nota**

O **unstack()** frequentemente substitui o **pivot()** em pipelines avançados

⚠️ Outro detalhe importante

O **unstack()** pode gerar NaN quando alguma comninação não existe

## 2.2 Multindex

Normalmente um DataFrame possu um único índice.

**Exemplo**

| index | Name | Age |
| ----- | ---- | --- |
| 0     | John | 22  |
| 1     | Anna | 38  |

Nesse caso, o índice é simples: 0,1,2,3....


**MultiIndex**: é quando o índice possui múltiplos níveis

| Sex    | Pclass | Fare |
| ------ | ------ | ---- |
| female | 1      | 106  |
| female | 2      | 21   |


pode virar

|Sex|Pclass|
|---| -----|
|female|  1|
|      |  2|
|male  |  1|

**Resumindo**: o multindex significar haver dimensões hierárquicas no índice.

| Operação           | Gera MultiIndex? |
| ------------------ | ---------------- |
| `groupby` múltiplo | ✅                |
| `stack()`          | ✅                |
| `pivot_table()`    | frequentemente   |
| `agg()` múltiplo   | nas colunas      |

Vantagens do multiindex():
- agrupamentos hierárquicos
- navegação dimensional
- reshaping avançado

In [94]:
grupo = (
    df.groupby(
        ['Sex', 'Pclass']
    )['Survived']
    .mean()
)
grupo

Sex     Pclass
Homem   1         0.368852
        2         0.157407
        3         0.135447
Mulher  1         0.968085
        2         0.921053
        3         0.500000
Name: Survived, dtype: float64

Acessando valores

In [95]:
grupo.loc['Mulher']

Pclass
1    0.968085
2    0.921053
3    0.500000
Name: Survived, dtype: float64

In [96]:
grupo.loc[('Mulher', 1)]

np.float64(0.9680851063829787)

Transformando em colunas

In [97]:
grupo.reset_index()

      Sex  Pclass  Survived
0   Homem       1  0.368852
1   Homem       2  0.157407
2   Homem       3  0.135447
3  Mulher       1  0.968085
4  Mulher       2  0.921053
5  Mulher       3  0.500000

Níveis do índice

In [98]:
grupo.index.names

FrozenList(['Sex', 'Pclass'])

Número de níveis

In [99]:
grupo.index.nlevels

2

Convertendo níveis em colunas

In [100]:
grupo.unstack()

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

**Outro detalhe importante**

MultiIndex pode existir nas linhas e nas colunas

In [101]:
df.groupby('Pclass').agg({
    'Fare': ['mean', 'max'],
    'Age': ['mean', 'median']
})

             Fare                  Age
             mean       max       mean median
Pclass
1       84.154687  512.3292  38.233441   37.0
2       20.662183   73.5000  29.877630   29.0
3       13.675550   69.5500  25.140620   24.0

In [102]:
df.groupby('Pclass').agg({
    'Fare': ['sum', 'mean'],
    'Age': ['median'],
    'PassengerId': ['count'],
    'Survived': ['mean']
})

              Fare               Age PassengerId  Survived
               sum       mean median       count      mean
Pclass
1       18177.4125  84.154687   37.0         216  0.629630
2        3801.8417  20.662183   29.0         184  0.472826
3        6714.6951  13.675550   24.0         491  0.242363

1.3 Visualização Analítica
A **visualização analítica** é organizar dados de forma que padrões, comparações e relações fiquem evidentes.

**Exemplo**

| PassengerId | Sex    | Pclass | Survived |
| ----------- | ------ | ------ | -------- |
| 1           | male   | 3      | 0        |
| 2           | female | 1      | 1        |


Aqui os padrões estão escondidos.

In [103]:
df.pivot_table(
    values='Survived',
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
)

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

Isso já é visualização analítica mesmo sem gráfico, pois a estrutura:
- destaca padrões
- facilita comparação
- organiza dimensões

O foco muda de “mostrar dados” para “evidenciar comportamento”

Os padrões mostram:

| Sex    | 1ª Classe  | 2ª Classe   | 3ª Classe  |
| ------ | ---------- | ----------- | ---------- |
| female | muito alta | alta        | moderada   |
| male   | baixa      | muito baixa | baixíssima |

E isso revela algo importante: Não era apenas **sexo** mas também **classe social**

## 2.3 Cruzamento de dimensões

Basicamente é analisar uma métrica através de múltiplas categorias ao mesmo tempo


**Exemplo no Titanic**

Você NÃO quer apenas a taxa geral de sobrevivência

Você quer:

- sobrevivência por sexo E classe

ou:

- sexo + idade + embarque

**Exemplo clássico de dimensões**
| Dimensão  | Exemplo      |
| --------- | ------------ |
| tempo     | ano, mês     |
| geografia | país, estado |
| produto   | categoria    |
| cliente   | sexo, idade  |
| classe    | Pclass       |

**E a métrica?**

É o valor analisado.

Exemplo:
- vendas
- lucro
- sobrevivência
- média
- quantidade

In [104]:
# Exemplo 01 - sobrevivência por sexo e classe
df.pivot_table(
    values='Survived',
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
)

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

In [105]:
#Exemplo 2 — idade média por sexo e embarque

df.pivot_table(
    values='Age',
    index='Sex',
    columns='Embarked',
    aggfunc='mean'
)

# nesse exemplo cruzamo sexo e porto de embarque

Embarked          C          Q          S
Sex
Homem     32.998841  30.937500  30.291440
Mulher    28.344262  24.291667  27.771505

In [106]:
# Exemplo 3 — múltiplas dimensões

df.groupby(
    ['Sex', 'Pclass', 'Embarked']
)['Fare'].mean()

Sex     Pclass  Embarked
Homem   1       C            93.536707
                Q            90.000000
                S            52.949947
        2       C            25.421250
                Q            12.350000
                S            19.232474
        3       C             9.352237
                Q            11.924251
                S            13.307149
Mulher  1       C           115.640309
                Q            90.000000
                S            99.026910
        2       C            25.268457
                Q            12.350000
                S            21.912687
        3       C            14.694926
                Q            10.307833
                S            18.670077
Name: Fare, dtype: float64

E aqui aparece um conceito MUITO importante: **Granularidade**

Quanto mais dimensões: mais específico fica o grupo

**Apenas sexo**

| Sex    | Survival |
| ------ | -------- |
| female | 0.74     |

**Sexo + classe**

| Sex    | Pclass | Survival |
| ------ | ------ | -------- |
| female | 1      | 0.96     |

⚠️ Mas existe um perigo:

Quanto mais dimensões, mais fragmentados os dados ficam

E aqui nasce um pensamento analítico importante: “qual o nível correto de granularidade?”

## 2.4 - Tabelas matriciais

As “Tabelas matriciais” são praticamente a evolução natural de:
- groupby
- pivot_table
- cruzamento de dimensões

**Definição**

É uma tabela onde linhas e colunas representam dimensões e as células representam métricas agregadas

**Estrutura**

| Dimensão linha | Dimensão coluna | Métrica |
| -------------- | --------------- | ------- |

In [107]:
df.pivot_table(
    values='Survived',
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
)

Pclass         1         2         3
Sex
Homem   0.368852  0.157407  0.135447
Mulher  0.968085  0.921053  0.500000

**Isso é uma matriz analítica.**

Porque o cérebro detecta padrões espaciais rapidamente

**🔍 Você imediatamente percebe:**
- mulheres sobreviveram mais
- 1ª classe teve vantagem
- homens da 3ª classe tiveram baixa sobrevivência

**🚀 Isso é MUITO usado em:**
- BI
- dashboards
- relatórios executivos
- análise exploratória

E aqui aparece um conceito importante: **Interseção dimensional**

Cada célula da matriz representa:uma combinação de dimensões

**Exemplo**

Célula: Mulher + class 1

↓

Resultado:0.96

In [108]:
##exemplo com métricas múltiplas

df.pivot_table(
    values=['Fare', 'Age'],
    index='Sex',
    columns='Pclass',
    aggfunc='mean'
)

              Age                              Fare
Pclass          1          2          3           1          2          3
Sex
Homem   41.281386  30.740707  26.507589   67.226127  19.741782  12.661633
Mulher  34.611765  28.722973  21.750000  106.125798  21.970121  16.118810

In [109]:
df.pivot_table(
    values='Fare',
    index='Sex',
    columns='Pclass',
    aggfunc='mean',
    margins=True # inclui as colunas de totais
)

Pclass           1          2          3        All
Sex
Homem    67.226127  19.741782  12.661633  25.523893
Mulher  106.125798  21.970121  16.118810  44.479818
All      84.154687  20.662183  13.675550  32.204208

**Adiciona os totais gerais**

Isso é MUITO parecido com a tabela dinâmica do Excel.

In [110]:
df.pivot_table(
    values='Survived',
    index='Embarked',
    columns='Pclass',
    aggfunc='mean',
    fill_value=0 #evita o NaN
)

Pclass           1         2         3
Embarked
C         0.694118  0.529412  0.378788
Q         0.500000  0.666667  0.375000
S         0.582677  0.463415  0.189802

# Parte 3 - Junção de DataFrames

| Situação           | Método            |
| ------------------ | ----------------- |
| relacionar tabelas | `merge()`         |
| empilhar linhas    | `concat()`        |
| juntar pelo índice | `join()`          |
| preencher NaN      | `combine_first()` |
| atualizar valores  | `update()`        |

## 3.1 merge()

O merge() é: uma das habilidades MAIS importantes do Pandas.

Porque praticamente todo projeto real usa:
- múltiplas fontes
- dimensões
- fatos
- enriquecimento de dados

Aqui o Pandas começa a parecer MUITO com :
- SQL
- Power BI
- bancos relacionais

**Temas abordados**

| Tema                     | Importância      |
| ------------------------ | ---------------- |
| `merge()` básico         | ALTÍSSIMA        |
| `on=`                    | fundamental      |
| `how=`                   | CRÍTICO          |
| `left/right/inner/outer` | ESSENCIAL        |
| joins 1:1 e 1:N          | MUITO importante |
| duplicação de linhas     | PERIGOSO         |
| merge vs map             | excelente tópico |
| chaves compostas         | profissional     |

### 3.1.1 Objetivos do Merge

O objetivo do Merge é Dataframes diferentes

Geralmente os dados
- entidades
- dimensões
- assuntos

**Exemplos**

**DataFrame passageiros**
|PassengerId|	Name|
|-------------|-----------------|
|1|	John|
|2|	Anna|

**DataFrame cabines**
|PassengerId|	Cabin|
|-----------|------|
|1|	C85|
|2|	B28|

**Merge**
```
df_passageiros.merge(
    df_cabines,
    on='PassengerId'
)
```
**Resultado**

|PassengerId|Name|Cabin|
|----------|-----|-----|
|1|John|C85|
|2|Anna|B28|


Então o merge funciona como “ligar tabelas por uma chave”
Aqui entra um conceito MUITO importante: **Chave**

No exemplo: PassengerId é a coluna usada para relacionar as tabelas


Isso é MUITO parecido com:
- SQL JOIN
- relacionamentos do Power BI
- PROCV/XLOOKUP do Excel

**Resumindo:** O merge() é praticamente o coração relacional do Pandas

**Principais temas**

| Tema          | Ideia                 |
| ------------- | --------------------- |
| `on=`         | qual coluna conecta   |
| `how='inner'` | interseção            |
| `left`        | preserva esquerda     |
| `right`       | preserva direita      |
| `outer`       | união total           |
| duplicações   | perigo real           |
| cardinalidade | conceito profissional |

**Nota**:

 Para essa sessão, quebraremos dividiremos o dataframe do titanic em 2 pois nas sessões anteriores fizemos alterações no dataframe. Então, importarei novamente.


**Documentação:** https://pandas.pydata.org/docs/reference/api/pandas.merge.html

Para essa sessão, quebraremos dividiremos o dataframe do titanic em 2.

nota: nas sessões anteriores fizemos alterações no dataframe. Então, importarei novamente.

In [111]:
url_2 = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df_titanic = pd.read_csv(url)

In [112]:
passageiros = df_titanic[ ['PassengerId', 'Name', 'Sex', 'Age'] ]
passageiros.head(5)

,PassengerId,Name,Sex,Age
0,1,"Braund, Mr. Owen Harris",male,22.0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,3,"Heikkinen, Miss. Laina",female,26.0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,5,"Allen, Mr. William Henry",male,35.0

In [113]:
embarque = df_titanic[
    ['PassengerId', 'Embarked', 'Fare']
]
embarque.head(5)

   PassengerId Embarked     Fare
0            1        S   7.2500
1            2        C  71.2833
2            3        S   7.9250
3            4        S  53.1000
4            5        S   8.0500

In [114]:
sobrevivencia = df_titanic[
    ['PassengerId', 'Survived']
]
sobrevivencia.head(5)

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0

In [115]:
passageiros.merge(
    sobrevivencia,
    on='PassengerId' # qual coluna conecta
)

,PassengerId,Name,Sex,Age,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1
2,3,"Heikkinen, Miss. Laina",female,26.0,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1
4,5,"Allen, Mr. William Henry",male,35.0,0
...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0
889,890,"Behr, Mr. Karl Howell",male,26.0,1
890,891,"Dooley, Mr. Patrick",male,32.0,0

### 3.1.2 Tipos de merge
Os tipos de merge são:
- INNER JOIN : mantém apenas as correspondêcias

In [116]:
passageiros.merge(
    sobrevivencia,
    on='PassengerId',
    how='inner'
)

#Resultado: Somente passageiros que existem nas duas tabelas

,PassengerId,Name,Sex,Age,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1
2,3,"Heikkinen, Miss. Laina",female,26.0,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1
4,5,"Allen, Mr. William Henry",male,35.0,0
...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0
889,890,"Behr, Mr. Karl Howell",male,26.0,1
890,891,"Dooley, Mr. Patrick",male,32.0,0

LEFT JOIN: mantém TODA a tabela da esquerda
Onde não houve match retornará NaN

In [117]:
passageiros.merge(
    sobrevivencia,
    on='PassengerId',
    how='left'
)

,PassengerId,Name,Sex,Age,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1
2,3,"Heikkinen, Miss. Laina",female,26.0,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1
4,5,"Allen, Mr. William Henry",male,35.0,0
...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0
889,890,"Behr, Mr. Karl Howell",male,26.0,1
890,891,"Dooley, Mr. Patrick",male,32.0,0

OUTER JOIN: TODOS os registros de ambas as tabelas

In [118]:
passageiros.merge(
    sobrevivencia,
    on='PassengerId',
    how='outer'
)

,PassengerId,Name,Sex,Age,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1
2,3,"Heikkinen, Miss. Laina",female,26.0,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1
4,5,"Allen, Mr. William Henry",male,35.0,0
...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0
889,890,"Behr, Mr. Karl Howell",male,26.0,1
890,891,"Dooley, Mr. Patrick",male,32.0,0

RIGHT JOIN: Mantém toda a tabela da direita

In [119]:
passageiros.merge(
    sobrevivencia,
    on='PassengerId',
    how='right'
)

,PassengerId,Name,Sex,Age,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1
2,3,"Heikkinen, Miss. Laina",female,26.0,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1
4,5,"Allen, Mr. William Henry",male,35.0,0
...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0
889,890,"Behr, Mr. Karl Howell",male,26.0,1
890,891,"Dooley, Mr. Patrick",male,32.0,0

| Join  | Mantém           |
| ----- | ---------------- |
| inner | interseção       |
| left  | tudo da esquerda |
| right | tudo da direita  |
| outer | união total      |

3.1.1 Múltiplas chaves

🔍 Exemplo

Imagine que PassengerId não é suficiente, então precisamos:
- Sex
- Pclass

```
df1.merge(
    df2,
    on=['Sex', 'Pclass']
)
```

In [120]:
media_idade = (
    passageiros.groupby(
        ['Sex', 'Age']
    )
    .size()
    .reset_index(name='Qtd')
)

In [121]:
media_idade

        Sex    Age  Qtd
0    female   0.75    2
1    female   1.00    2
2    female   2.00    6
3    female   3.00    2
4    female   4.00    5
..      ...    ...  ...
140    male  70.00    2
141    male  70.50    1
142    male  71.00    2
143    male  74.00    1
144    male  80.00    1

[145 rows x 3 columns]

In [122]:
media_tarifa = (
  df_titanic.groupby(
        ['Sex', 'Age']
    )['Fare']
    .mean()
    .reset_index()
)

In [123]:
media_tarifa

        Sex    Age       Fare
0    female   0.75  19.258300
1    female   1.00  13.437500
2    female   2.00  43.245833
3    female   3.00  31.327100
4    female   4.00  22.828340
..      ...    ...        ...
140    male  70.00  40.750000
141    male  70.50   7.750000
142    male  71.00  42.079200
143    male  74.00   7.775000
144    male  80.00  30.000000

[145 rows x 3 columns]

In [124]:
#merge composto
media_idade.merge(
    media_tarifa,
    on=['Sex', 'Age'],
    how='inner'
)

        Sex    Age  Qtd       Fare
0    female   0.75    2  19.258300
1    female   1.00    2  13.437500
2    female   2.00    6  43.245833
3    female   3.00    2  31.327100
4    female   4.00    5  22.828340
..      ...    ...  ...        ...
140    male  70.00    2  40.750000
141    male  70.50    1   7.750000
142    male  71.00    2  42.079200
143    male  74.00    1   7.775000
144    male  80.00    1  30.000000

[145 rows x 4 columns]

In [125]:
sobrev_embarque = (
    df_titanic.groupby(
        ['Sex', 'Embarked']
    )['Survived']
    .mean()
    .reset_index()
)
sobrev_embarque

      Sex Embarked  Survived
0  female        C  0.876712
1  female        Q  0.750000
2  female        S  0.689655
3    male        C  0.305263
4    male        Q  0.073171
5    male        S  0.174603

In [126]:
fare_embarque = (
    df_titanic.groupby(
        ['Sex', 'Embarked']
    )['Fare']
    .mean()
    .reset_index()
)
fare_embarque

      Sex Embarked       Fare
0  female        C  75.169805
1  female        Q  12.634958
2  female        S  38.740929
3    male        C  48.262109
4    male        Q  13.838922
5    male        S  21.711996

In [127]:
sobrev_embarque.merge(
    fare_embarque,
    on=['Sex', 'Embarked']
)

      Sex Embarked  Survived       Fare
0  female        C  0.876712  75.169805
1  female        Q  0.750000  12.634958
2  female        S  0.689655  38.740929
3    male        C  0.305263  48.262109
4    male        Q  0.073171  13.838922
5    male        S  0.174603  21.711996

###3.2 Concat()

O concat() é um método do pandas usado para unir DataFrames ou Series de forma estrutural, empilhando os dados verticalmente (axis=0) ou horizontalmente (axis=1).

Diferente do merge(), que relaciona tabelas por chaves em comum, o concat() simplesmente combina estruturas mantendo seus dados originais e alinhando-os pelos índices quando necessário.

Ele é muito utilizado para juntar arquivos mensais, consolidar múltiplos datasets, empilhar tabelas semelhantes ou adicionar colunas lado a lado em processos de ETL e análise de dados.

**Sintaxe básica:** `pd.concat([df1, df2])`

**Documentação:**: https://pandas.pydata.org/docs/reference/api/pandas.concat.html

#### 3.2.1 Concat vertical (axis=0)

Nesse caso, o pandas empilha uma tabela abaixo da outra

Como as colunas são diferentes o Pandas cria a união das colunas

E onde faltar dado?
- aparece NaN

O concat() não faz relacionamento

In [128]:
pd.concat([
    passageiros,
    embarque
])

,PassengerId,Name,Sex,Age,Embarked,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN
2,3,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN
4,5,"Allen, Mr. William Henry",male,35.0,NaN,NaN
...,...,...,...,...,...,...
886,887,NaN,NaN,NaN,S,13.00
887,888,NaN,NaN,NaN,S,30.00
888,889,NaN,NaN,NaN,S,23.45
889,890,NaN,NaN,NaN,C,30.00
890,891,NaN,NaN,NaN,Q,7.75

#### 3.2.2 Concat horizontal (axis=1)

In [129]:
pd.concat([
    passageiros,
    embarque
], axis=1)

,PassengerId,Name,Sex,Age,PassengerId,Embarked,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,1,S,7.2500
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,2,C,71.2833
2,3,"Heikkinen, Miss. Laina",female,26.0,3,S,7.9250
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,4,S,53.1000
4,5,"Allen, Mr. William Henry",male,35.0,5,S,8.0500
...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,887,S,13.0000
887,888,"Graham, Miss. Margaret Edith",female,19.0,888,S,30.0000
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,889,S,23.4500
889,890,"Behr, Mr. Karl Howell",male,26.0,890,C,30.0000
890,891,"Dooley, Mr. Patrick",male,32.0,891,Q,7.7500

**Diferença essencial**
- merge(): “relacione os dados”
- concat(): “cole as estruturas”

Índices no concat

O alinhamento ocorre pelos índices
**Exemplo**

Se:passageiros.index

↓

`0 1 2 3`

e:

embarque.index

↓

`0 1 2 3`
O concat horizontal funciona perfeitamente.

Mas se os índices forem diferentes:

o Pandas tentará alinhar por posição do índice e não pela ordem visual.

**Muito importante:** `ignore_index=True`

In [130]:
pd.concat([
    passageiros,
    embarque
], ignore_index=True)

,PassengerId,Name,Sex,Age,Embarked,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN
2,3,"Heikkinen, Miss. Laina",female,26.0,NaN,NaN
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN
4,5,"Allen, Mr. William Henry",male,35.0,NaN,NaN
...,...,...,...,...,...,...
1777,887,NaN,NaN,NaN,S,13.00
1778,888,NaN,NaN,NaN,S,30.00
1779,889,NaN,NaN,NaN,S,23.45
1780,890,NaN,NaN,NaN,C,30.00
1781,891,NaN,NaN,NaN,Q,7.75

**O que faz?**

Recria um novo índice sequencial

Isso é muito usado quando:
- empilhamos arquivos
- juntamos meses
- consolidamos datasets

In [131]:
pd.concat(
    [passageiros, embarque],
    keys=['passageiros', 'embarque']
)

                 PassengerId  \
passageiros 0              1
            1              2
            2              3
            3              4
            4              5
...                      ...
embarque    886          887
            887          888
            888          889
            889          890
            890          891

                                                              Name     Sex  \
passageiros 0                              Braund, Mr. Owen Harris    male
            1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
            2                               Heikkinen, Miss. Laina  female
            3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
            4                             Allen, Mr. William Henry    male
...                                                            ...     ...
embarque    886                                                NaN     NaN
            887                                                NaN     NaN
            888                                                NaN     NaN
            889                                                NaN     NaN
            890                                                NaN     NaN

                  Age Embarked   Fare
passageiros 0    22.0      NaN    NaN
            1    38.0      NaN    NaN
            2    26.0      NaN    NaN
            3    35.0      NaN    NaN
            4    35.0      NaN    NaN
...               ...      ...    ...
embarque    886   NaN        S  13.00
            887   NaN        S  30.00
            888   NaN        S  23.45
            889   NaN        C  30.00
            890   NaN        Q   7.75

[1782 rows x 6 columns]

Outro parâmetro útil :keys=

Nesse caso é criado um multindex que é muito usado para:
- rastrear origem
- auditoria
- ETL

In [132]:
pd.concat(
    [passageiros, embarque],
    keys=['passageiros', 'embarque']
)

                 PassengerId  \
passageiros 0              1
            1              2
            2              3
            3              4
            4              5
...                      ...
embarque    886          887
            887          888
            888          889
            889          890
            890          891

                                                              Name     Sex  \
passageiros 0                              Braund, Mr. Owen Harris    male
            1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
            2                               Heikkinen, Miss. Laina  female
            3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
            4                             Allen, Mr. William Henry    male
...                                                            ...     ...
embarque    886                                                NaN     NaN
            887                                                NaN     NaN
            888                                                NaN     NaN
            889                                                NaN     NaN
            890                                                NaN     NaN

                  Age Embarked   Fare
passageiros 0    22.0      NaN    NaN
            1    38.0      NaN    NaN
            2    26.0      NaN    NaN
            3    35.0      NaN    NaN
            4    35.0      NaN    NaN
...               ...      ...    ...
embarque    886   NaN        S  13.00
            887   NaN        S  30.00
            888   NaN        S  23.45
            889   NaN        C  30.00
            890   NaN        Q   7.75

[1782 rows x 6 columns]

## 3.2 Join


O join() é uma forma simplificada de realizar merges baseados em índices, permitindo combinar DataFrames horizontalmente de maneira rápida e legível. Ele é especialmente útil quando o índice já representa a chave relacional dos dados, evitando a necessidade de especificar explicitamente colunas com on= como no merge().


**<center>Join X Merge</center>**

**merge():** normalmente usa colunas

**join():** normalmente usa índices

In [133]:
passageiros_idx = passageiros.set_index('PassengerId')

embarque_idx = embarque.set_index('PassengerId')

In [134]:
passageiros_idx.join(
    embarque_idx
)

,Name,Sex,Age,Embarked,Fare
PassengerId,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,S,7.2500
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,C,71.2833
3,"Heikkinen, Miss. Laina",female,26.0,S,7.9250
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,S,53.1000
5,"Allen, Mr. William Henry",male,35.0,S,8.0500
...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,S,13.0000
888,"Graham, Miss. Margaret Edith",female,19.0,S,30.0000
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,S,23.4500
890,"Behr, Mr. Karl Howell",male,26.0,C,30.0000
891,"Dooley, Mr. Patrick",male,32.0,Q,7.7500

**Comparativo**

**merge**
```
passageiros.merge(
    embarque,
    on='PassengerId'
)
```

**join()**
```
passageiros_idx.join(
    embarque_idx
)
```

**Tipo de join**

Assim como no merge: `how='left'`

**Exemplo**

```
passageiros_idx.join(
    embarque_idx,
    how='inner'
)
```

O join aceita
- left
- right
- inner
- outer


**Vantagem do join**
Menor sintaxe

| Merge | Join |
| :--- | :--- |
| <pre><code>passageiros.merge(<br>  embarque,<br>  on='PassengerId',<br>  how='left'<br>)</code></pre> | <pre><code>passageiros_idx.join(<br>  embarque_idx,<br>  how='left'<br>)</code></pre> |
| |


**Nota:**
Igual ao merge, o join também pode:
- duplicar linhas
- gerar NaN
- sofrer com cardinalidade

**Resumo:**

| Situação                | Melhor escolha |
| ----------------------- | -------------- |
| chaves em colunas       | `merge()`      |
| chaves no índice        | `join()`       |
| sintaxe rápida          | `join()`       |
| relacionamento complexo | `merge()`      |

## 3.3 combine_first()

O combine_first() combina dois DataFrames priorizando os valores do primeiro e utilizando os valores do segundo apenas onde existirem dados ausentes (NaN). Ele é muito útil em processos de limpeza, consolidação e recuperação de dados incompletos, funcionando como uma espécie de “fallback” entre estruturas compatíveis.

In [135]:
passageiros_nan = passageiros.copy()

In [136]:
# remomvendo alguns valores
passageiros_nan.loc[
    [0, 3, 5],
    'Age'
] = np.nan

In [137]:
#base de apoio
idades_backup = passageiros[
    ['PassengerId', 'Age']
]

In [138]:
#transformando o índice
passageiros_nan = passageiros_nan.set_index('PassengerId')
idades_backup = idades_backup.set_index('PassengerId')

A etapa acima  é importante pois o **combine_fist()** alinha pelos índice

In [139]:
resultado = passageiros_nan.combine_first(
    idades_backup
)
resultado

              Age                                               Name     Sex
PassengerId
1            22.0                            Braund, Mr. Owen Harris    male
2            38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3            26.0                             Heikkinen, Miss. Laina  female
4            35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5            35.0                           Allen, Mr. William Henry    male
...           ...                                                ...     ...
887          27.0                              Montvila, Rev. Juozas    male
888          19.0                       Graham, Miss. Margaret Edith  female
889           NaN           Johnston, Miss. Catherine Helen "Carrie"  female
890          26.0                              Behr, Mr. Karl Howell    male
891          32.0                                Dooley, Mr. Patrick    male

[891 rows x 3 columns]

🧠 O que acontece?

O Pandas:
- mantém os valores existentes
- procura NaN
- tenta preencher usando o outro DataFrame

**Antes**

| PassengerId | Age |
| ----------- | --- |
| 1           | 22  |
| 2           | NaN |

**Backup**
| PassengerId | Age |
| ----------- | --- |
| 1           | 22  |
| 2           | 38  |

**Resultado**
| PassengerId | Age |
| ----------- | --- |
| 1           | 22  |
| 2           | 38  |

**Diferença para merge**

|merge()|combine_first()|
|-------|---------------|
|junta estruturas|preenche faltantes|

**Diferença para fillna**

O fillna() normalmente usa:
- valor fixo
- média
- constante

`df['Age'].fillna(0)`

Já o combine_first() usa dados reais de outro DataFrame

Isso é MUITO útil em:
- ETL
- reconciliação
- múltiplas fontes
- bases complementares

## 3.4 Update()

O update() modifica um DataFrame existente utilizando valores de outro DataFrame alinhados por índice e coluna. Diferente do merge() ou concat(), ele não adiciona novas linhas ou colunas; apenas atualiza valores já existentes, sendo muito útil para correções, patches e sincronização de dados.

**Ideia central:** atualizar valores existentes usando outro DataFrame

**Diferença IMPORTANTE**

- O combine_first() preenche apenas NaN
- O update() sobrescreve valores existentes

 **⚠️Muito importante**

O update() modifica o DataFrame original Diferente de muitos métodos do Pandas.

O update() faz mutação inplace

**Então:** `resultado = passageiros.update(...)` retornará None.
Porque ele altera diretamente passageiros

**Outro detalhe importante**

O update() não cria novas linhas nem novas colunas

In [140]:
#criaremos uma cópia do nosso df_passageiros
passageiros_update = passageiros.copy()

In [141]:
#DataFrame de atualização
correcoes = pd.DataFrame({
    'Age': [99, 77]
},
index=[0, 3])

In [142]:
correcoes

   Age
0   99
3   77

In [143]:
passageiros_update.update(correcoes)